### ISSUE TITLE
The player button is missing

### ISSUE THREAD

**Issue by whitersun** [Yizack/nuxt-musicfyplayer#1]
After test and play audio from your demo website, after end music. The player button missing no return or play again, can I ask this is bug? I test nuxt-musicfplayer have the same is local project.

you can try in your demo
https://dimatis.yizack.com/

**Comment by Yizack** [comment]
The replay icon was missing! thank you for reporting, I just added it, it's going to be available next release!
- #2 

![image](https://github.com/user-attachments/assets/22a709f7-be50-450d-b67e-da90207f9d2d)
